baseURL = 'https://spatialvesselanalysis.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = 'hugo-book'

[params]
  BookMenuBundle = '/projects/'
  BookSection = '*'
  BookToC = true
  math = true
  disableSearch = true
  BookSearch = false

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Step-by-Step Guide"
    url = "/projects/"
    weight = 1

  [[menu.main]]
  identifier = "about"
  name = "About Us"
  url = "/about/"
  weight = 99
  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true